[project]
authors = [
  "Albert Steppi <albert.steppi@gmail.com>",
  "Irwin Zaid <irwin.zaid@gmail.com>",
]
channels = ["https://prefix.dev/conda-forge"]
description = "Special function implementations."
name = "xsf"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

## Build

[feature.build.dependencies]
cmake = ">=3.30.5,<4"
cxx-compiler = ">=1.8.0,<2"
make = ">=4.4.1,<5"

[feature.build.tasks.configure]
cmd = [
  "cmake",
  # The source is in the root directory
  "-S .",
  # We want to build in the build directory
  "-B build",
]
cwd = "."

[feature.build.tasks.build-only]
# Just build without configure
cmd = ["cmake", "--build", "build"]
cwd = "."

[feature.build.tasks.build]
# Build with default configuration
depends-on = ["configure", "build-only"]

## Tests

[feature.tests.dependencies]
catch2 = ">=3.8.0,<4"
libarrow-all = ">=19.0.1,<20"

[feature.tests.tasks]
# clean xsref dir
clean-xsref = { cwd = ".", cmd = "rm -rf xsref" }
# clone xsref
clone-xsref.cmd = "git clone https://github.com/scipy/xsref.git"
clone-xsref.cwd = "."
clone-xsref.depends-on = ["clean-xsref"]
# configure cmake for tests
configure-tests.cmd = [
  "cmake",
  # Enable building tests
  "-DBUILD_TESTS=ON",
  # The source is in the root directory
  "-S .",
  # We want to build in the build directory
  "-B build",
]
configure-tests.cwd = "."
configure-tests.env.XSREF_TABLES_PATH = "$PWD/xsref/tables"
# build for tests
build-tests.depends-on = ["configure-tests", "build-only"]
# run tests
tests.cmd = ["ctest", "--output-on-failure", "--test-dir", "build/tests"]
tests.depends-on = ["clone-xsref", "build-tests"]
tests.cwd = "."

[feature.tests-ci.dependencies]
ccache = ">=4.11.2,<5"

[feature.tests-ci.tasks]
build-tests-ci.cmd = ["cmake", "--build", "build", "-j3"]
build-tests-ci.depends-on = ["clone-xsref", "configure-tests"]
build-tests-ci.cwd = "."

# run tests
tests-ci.cmd = ["ctest", "--output-on-failure", "--test-dir", "build/tests", "-j3"]
tests-ci.depends-on = ["build-tests-ci"]
tests-ci.cwd = "."

## Coverage

# [feature.coverage.dependencies]
# lcov = ">=1.16,<2"

# [feature.coverage.tasks.configure-coverage]
# cmd = [
#     "cmake",
#     "-DCMAKE_BUILD_TYPE=Coverage",
#     # The source is in the root directory
#     "-S .",
#     # We want to build in the build directory
#     "-B build",
# ]

# [feature.coverage.tasks.coverage]
# depends-on = ["configure-coverage"]
# cmd = ["cmake", "--build", "build", "--target", "coverage_html"]

# [feature.coverage.tasks.tests-coverage]
# # Generate the coverage report and then run tests under the same configuration
# depends-on = ["coverage"]
# cwd = "build"
# cmd = "ctest"

[environments]
default = { features = ["build", "tests"], solve-group = "default" }
tests-ci = { features = ["tests-ci"], solve-group = "default" }
