name: Tests

on: [ push, pull_request ]

permissions:
  contents: read  # to fetch code (actions/checkout)

env:
  CCACHE_DIR: "${{ github.workspace }}/.ccache"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: ${{ matrix.environment }} ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    env:
      XSREF_TABLES_PATH: "${{ github.workspace }}/xsref/tables"
    strategy:
      fail-fast: false
      matrix:
        environment: [tests-ci]
        runs-on: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: prefix-dev/setup-pixi@92815284c57faa15cd896c4d5cfb2d59f32dc43d # v0.8.3
        with:
          pixi-version: v0.44.0
          cache: true
          environments: ${{ matrix.environment }}
      - name: Run tests
        run: pixi run --environment=tests-ci tests-coverage-ci
      - name: Upload HTML coverage report
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882  # v4.4.3
        with:
          name: cov-html
          path: build/coverage_report/**
