name: Linux Tests

on: [ push, pull_request ]

permissions:
  contents: read  # to fetch code (actions/checkout)

env:
  CCACHE_DIR: "${{ github.workspace }}/.ccache"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  gcc_x86_64_linux:
    name: GCC X86_64 Linux
    runs-on: ubuntu-22.04
    env:
      XSREF_TABLES_PATH: "${{ github.workspace }}/xsref/tables"

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: prefix-dev/setup-pixi@92815284c57faa15cd896c4d5cfb2d59f32dc43d # v0.8.3
        with:
          pixi-version: v0.44.0
          cache: true
      - name: Run tests
        run: |
          pixi run configure-tests
          pixi run build-only -j2
          pixi run tests -j2    
